CREATE TABLE users (
    id VARCHAR PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    image TEXT,
    sizeId INT,
    role VARCHAR(50) NOT NULL CHECK (role IN ('user', 'admin', 'superuser')) DEFAULT 'user',
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prices (
    id INT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL,
    period VARCHAR(10) NOT NULL CHECK (period in ('MONTHLY', 'DAILY', 'YEARLY')) DEFAULT 'MONTHLY',
    currency VARCHAR(10) NOT NULL
);

CREATE TABLE propertySizes (
    id INT PRIMARY KEY,
    width DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    unit VARCHAR(50) NOT NULL CHECK (unit IN ('METER', 'FEET')) DEFAULT 'METER',
    depth DECIMAL(10, 2) NOT NULL
);

CREATE TABLE reviews (
    id INT PRIMARY KEY UNIQUE,
    message TEXT,
    rating INT NOT NULL CHECK (rating <= 5)
);

CREATE TABLE property (
    id INT PRIMARY KEY NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    isPopular BOOLEAN NOT NULL DEFAULT false,
    likeCount INTEGER DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    priceId INT,
    sizeId INT,
    reviewId INT,
    amenities TEXT[],
    FOREIGN KEY (priceId) REFERENCES prices(id),
    FOREIGN KEY (sizeId) REFERENCES propertySizes(id)
);

CREATE TABLE addresses (
    id INT PRIMARY KEY,
    propertyId INT,
    streetAddress VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postalCode VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE images (
    id INT PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    alt VARCHAR(255) DEFAULT 'property image',
    propertyId INT,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE wishlist (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE washrooms (
    washroomId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propertyId INT,
    type VARCHAR(10) NOT NULL CHECK (type in ('SHARED', 'ATTACHED')),
    count INT NOT NULL,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE singlerooms (
    propertyId INT PRIMARY KEY,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE doublerooms (
    propertyId INT PRIMARY KEY,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE bhkrooms (
    propertyId INT PRIMARY KEY,
    beds INT NOT NULL,
    halls INT NOT NULL,
    kitchen INT NOT NULL,
    balcony INT NOT NULL,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE sharedrooms (
    propertyId INT PRIMARY KEY,
    beds INT NOT NULL,
    halls INT NOT NULL,
    kitchen INT NOT NULL,
    balcony INT NOT NULL,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);

CREATE TABLE villas (
    propertyId INT PRIMARY KEY,
    swimmingpool BOOLEAN NOT NULL,
    beds INT NOT NULL,
    halls INT NOT NULL,
    kitchen INT NOT NULL,
    balcony INT NOT NULL,
    FOREIGN KEY (propertyId) REFERENCES property(id)
);